### PR TITLE
fix circular toctree references (probably caused by confusion from *.md extension)

### PR DESCRIPTION
**Pull request by simonwengert**
Fixes  Issue #168

### CODE REVIEW

**Comment by bernstei** [comment]
I have an idea  - those file are semi-automatically generated by `sphinx-apidoc -o source ../wfl`. It _is_ possible to deal with this semi-automatically (unlike what I wrote in the issue comments) by making this command in the docs `Makefile`, and adding `mv`/`sed` commands to rename the file and its reference. 

@simonwengert would you be able to do that, or should I close this PR and open a different one for my semi-automatic solution?

**Comment by simonwengert** [comment]
You meant something like that (see PR)?

**Comment by bernstei** [comment]
> You meant something like that (see PR)?

That's the right `sed`, command but right now it's modifying a github committed file.  I meant that all the files generated by the `sphix-apidoc` command need to be removed from the repo and instead generated dynamically by the `docs/Makefile` rule before the `sed`.

**Comment by bernstei** [comment]
replaced by #176

**Pull request closed without merging**
