### PR TITLE
Rename parallelized .run commands

### LINKED ISSUE #226: Change autoparallelized `.run` instances' names

### PR DESCRIPTION
**Pull request by gelzinyte**
Changes: 
- `generic.run()` -> `generic.calculate()`
- `wfl.map.run()` -> `wfl.map.map()` 
- `wfl.generate.md.sample()` -> `wfl.generate.md.md()`
- `wfl.generate.optimize.run()` -> `wfl.generate.optimize.optimize()`
- `wfl.generate.buildcell.run()` -> `wfl.generate.buildcell.buildcell()`
- `wfl.generate.minimahopping.run()` -> `wfl.generate.minimahopping.minimahopping()`
- `phonopy.run()` -> `phonopy.phonopy()`
- `smiles.run()` -> `smiles.smiles()`
- `wfl.descriptors.quippy.calc()` -> `wfl.descriptors.quippy.calculate()`

Closes #226

### CODE REVIEW

**Comment by gelzinyte** [comment]
@simonwengert @bernstei do these look reasonable? @bernstei would you mind running your complete tin pytest to make sure nothing's messed up?

**Comment by bernstei** [comment]
Yes, once the CI tests are successful I'll do the full test and let you know how it goes.

**Comment by bernstei** [comment]
@gelzinyte can you fix the one CI test that's failing before I do my full one?

**Comment by gelzinyte** [comment]
yes, this should be it, but I'll update this PR if any other tests fail too.

**Comment by gelzinyte** [comment]
I've moved them out in another PR, but it must also have contained one of the parallelized operations. Let me fix it.

**Comment by bernstei** [comment]
I'm happy with the new names, so you can merge as soon as it lets you.  It may not until the CI tests actually complete.

**Pull request merged**
