### PR TITLE
License

### PR DESCRIPTION
**Pull request by gelzinyte**
Does this look ok @gabor1 & @noambernstein ?

### CODE REVIEW

**Comment by bernstei** [comment]
@gelzinyte I'm happy to merge this, except there's an orca test xfail which probably doesn't belong.

**Comment by gelzinyte** [comment]
Orca xfail is/was there in the main branch (ORCA calculator needs to be updated, see #235 ). I've removed the duplicate xfail now, so this can be merged once the tests are done.

**Comment by bernstei** [comment]
Quite a few tests are failing.  Should we try merging from main, in case those were updated, to see if that makes the tests pass?

**Comment by bernstei** [comment]
made redundant by #308

**Pull request closed without merging**
