### PR TITLE
Doc example dimer structures

### PR DESCRIPTION
**Pull request by simonwengert**
Addresses one of the tasks defined in Issue #143.

### CODE REVIEW

**Comment by bernstei** [comment]
What do you think about moving the `assert` that's required for `pytest` to a separate code block, so as not to distract from the main example?  The automated `pytest` will have to run both, but in general I think it should run all code blocks, since some complex examples may want to break up the text that way.

**Comment by simonwengert** [comment]
It's even possible to then hide this assert-codeblock completely by adding `"nbsphinx": "hidden",` to the meta data in the ipynb. In this way we can display our examples as we had before and can still use the assert-codeblocks for our pytests.

**Comment by bernstei** [comment]
Could you hide the test `assert` cell in the buildcell example/test as well?

**Comment by bernstei** [comment]
> I open the ipynb file via `vim` and added that line manually.

Do we need that documented someplace?  Is there a "guide to making examples", or if not, should there be one?

**Pull request merged**
