### PR TITLE
Geometry optimisation - keep constraints from atoms objects 

### PR DESCRIPTION
**Pull request by LarsSchaaf**
Constraints (ie FixedAtoms) that are part of the atoms object that is being optimised get overwritten when specifying the symmetry command. Now its possible to clear the ase.Atoms object's constraints as previously or keep them.

### CODE REVIEW

**Comment by bernstei** [comment]
I tend to lean to making things simpler, so not having yet another flag to clear constraints.  Just always append the symmetrization constraint to any existing ones, and remove it at the end.  Can you implement that?

**Comment by bernstei** [comment]
Good, except that `clear_constraints` is still an argument to the low level function, and it's just ignored. 

How hard would it be to add a test for this (i.e. do a minim with a constraint and symmetrization and confirm that the constraint is there at the output)?

**Comment by LarsSchaaf** [comment]
Yes can do !

**Comment by LarsSchaaf** [comment]
Had accidentally formatted the test script with `black` [reason for forced push to my own fork]. 

Let me know if the test is what you imagined.

**Comment by bernstei** [comment]
Looks good, but do you understand why the tests aren't running?  Is it just because it's in your fork?

**Comment by bernstei** [comment]
@LarsSchaaf can you create this branch in _this_ repo, so we can see the test results?

**Comment by bernstei** [comment]
I'm happy to merge, but curious - why did you change the test? Was it failing when you compared actual constraint objects?

**Comment by LarsSchaaf** [comment]
Yes exactly. I didn't really see a quick way to compare constraint objects. Happy to change it if there's a trivial way!


https://stackoverflow.com/questions/1227121/compare-object-instances-for-equality-by-their-attributes

**Comment by bernstei** [comment]
Thanks.  I'll merge now.

**Pull request merged**
