### PR TITLE
rollup of various updates, most importantly gap-rss energy sigma proportional to sqrt(Nat)

### PR DESCRIPTION
**Pull request by bernstei**
Add support for more complex temperature schedules in MD sampling, and multiple vacancies (random and clustered).  Also add tests of these functionalities.

Add support for generating multiple vacancies in gap_rss_iter_fit.py, also add functionality to point defect generation test.

Scale programmatically set energy, virial, and hessian sigmas by sqrt(len(at)), as per issue #36

Allow different buildcell inputs for different step types.

Use different random minimum for each defect MD supercell

Add params to allow different flat histogram kT bias in selection of minima and selection of final fitting configurations.

Add params to set vol and composition range for "nearby" configurations when doing E_per_atom_dist_to_nearby for flat histogram.

Update gap-rss test reference values to be consistent with new functionality and heuristics.

### CODE REVIEW

**Comment by bernstei** [comment]
closes #36

**Comment by bernstei** [comment]
Anyone, @gelzinyte @gabor1 ? Or should I just merge?

**Comment by gabor1** [comment]
Sorry I'm scrambling to keep up while traveling. Will try to have a look at it tonight, but if you are tired of waiting, just merge

**Comment by bernstei** [comment]
I don't mind waiting.  I just wanted confirmation that someone else might be willing to look at it.

**Comment by bernstei** [comment]
@gabor1 do you want to look over this, at least the new energy sigma heuristics, so we can go on to everything else? Or nominated someone else to review it?

**Pull request merged**
