### PR TITLE
Add ipython to docs.yml for syntax highlighting

### PR DESCRIPTION
**Pull request by bernstei**
@simonwengert do you think this should do it?

### CODE REVIEW

**Comment by simonwengert** [comment]
Yes, that's what I meant (in issue #204)

**Comment by bernstei** [comment]
OK, I'll merge and see if it fixes the online docs.

**Comment by simonwengert** [comment]
Doesn't seem to have fixed it, yet. In the `Build Documentation` section in `build-docs` it still states `/home/runner/work/workflow/workflow/docs/source/examples.buildcell.ipynb:: WARNING: Pygments lexer name 'ipython3' is not known` for all the *.ipynb although `ipython` should be installed now.

**Comment by bernstei** [comment]
Some discussion here https://github.com/spatialaudio/nbsphinx/issues/24 I'll see if I can glean any useful suggestions from that thread.

**Pull request merged**
