### PR TITLE
rewrite ConfigSet and OutputSpec

### PR DESCRIPTION
**Pull request by bernstei**
Major rewrite of config input/output abstraction, with a few goals:
 - generally clean up the code
 - support nested structures (lists of lists .... ) both in memory and in files

### CODE REVIEW

**Comment by bernstei** [comment]
Remaining failing tests are phono3py, which can't be imported because conda is broken (see https://github.com/conda-forge/h5py-feedstock/issues/121)

**Comment by bernstei** [comment]
@simonwengert can you take a look at the way I modified `test_minimahopping.py` in https://github.com/libAtoms/workflow/pull/145/commits/8cde0975b18073748f3528eefa232164cecd3332 so it doesn't need to know about the internals of the `ConfigSet` object?

I'm pretty sure I understand what it's doing, and the tests pass, but since you committed that code, I'd appreciate a confirmation that I didn't break anything.

**Comment by gelzinyte** [comment]
Looks good to me, thanks for the update!

**Comment by bernstei** [comment]
OK - this is built on top of the autopara info, so I'll merge after that is done.

**Pull request merged**
